日本語(im@s)にタグTLカラム設定の翻訳を追加
imas/mastodon pull request #124
Opened 2017-12-17 17:22 UTC by takayamaki

2017-12-28 09:09 UTC, deflis reviewed
相当箇所のja.json

```
  "tag.settings": "カラム設定",
  "tag.column_settings.advanced": "上級者向け",
  "tag.column_settings.basic": "基本設定",
  "tag.column_settings.filter_regex": "ミュートするキーワード(縦棒「|」区切り)",
  "tag.column_settings.show_local_only": "ローカルのみ表示",
  "tag.add_favourite.public": "お気に入り登録(公開)",
  "tag.add_favourite.unlisted": "お気に入り登録(未収載)",
  "tag.remove_favourite": "お気に入り解除",
```

2017-12-28 09:11 UTC, deflis requested changes

2017-12-28 09:11 UTC, deflis commented on app/javascript/mastodon/locales/ja-IM.json
> +  "tag.column_settings.basic": "基本設定",
advancedの訳は `MASTER` で、basicの訳は `REGURAR` なので合わせたほうが良さそう。

2018-01-05 01:55 UTC, YaQ00 commented on app/javascript/mastodon/locales/ja-IM.json
> +  "tag.remove_favourite": "スウィーティーじゃない",
・スウィーティー多用しすぎ
・公開と未収載はアイマス語ではない

この二点から、favourite系の日本語訳は別のものにした方がいいかも。例えば
スウィーティー☆（公開）→世界レベルで公開（楽屋）
（未収載）→子豚ちゃんの遊び場（オフィス）
じゃない→ノースウィーティー
とか？

2018-01-09 02:08 UTC, oden commented on app/javascript/mastodon/locales/ja-IM.json
> +  "tag.remove_favourite": "スウィーティーじゃない",
公演とかリハーサルとかですかね

2018-01-29 17:07 UTC, deflis approved these changes
:+1:

2018-01-29 17:14 UTC, merged