tagTLのstreaming APIについて、認証時にはpublicとunlistedを、未認証時にはpublicのみを配送するように変更
imas/mastodon pull request #132
Opened 2018-01-30 18:38 UTC by takayamaki

表題通りです。

Server Side Eventsの場合もWebSocketの場合も
 https://github.com/imas/mastodon/blob/ccf4f170de86f24d5a243c411b807f1c394723cf/streaming/index.js#L219-L240 を通ります。

accountFromRequest関数はRequest headerまたはquery stringにtokenが指定されていた場合はエンドポイントが認証不要かどうかに関わらず https://github.com/imas/mastodon/blob/ccf4f170de86f24d5a243c411b807f1c394723cf/streaming/index.js#L188-L217 にてtokenの照会を行います。

accountFromToken関数は照会したtokenが正しいtokenだった場合に必ずreq.accountIdにそのtokenの所有者のaccountIdを代入するため、 https://github.com/imas/mastodon/blob/ccf4f170de86f24d5a243c411b807f1c394723cf/streaming/index.js#L468-L474 および https://github.com/imas/mastodon/blob/ccf4f170de86f24d5a243c411b807f1c394723cf/streaming/index.js#L519-L524 の時点ではreq.accountIdがundefinedかそうでないかによって認証の有無を判別することができます。

related #123

2018-01-31 08:59 UTC, fvh-P requested changes
Chromeで以下の画像のように `Uncaught TypeError`が発生し、タグTLのみリアルタイムに更新されません。im@stodonのstableなバージョンに戻したところ、このエラーは発生しなくなりました。
詳細な原因まではわかりませんでした。確認お願いします。こちらでも引き続き調査します。
![err](https://user-images.githubusercontent.com/8458066/35607056-b21cb78a-0695-11e8-9de3-0f5abe7f7051.PNG)

2018-01-31 22:19 UTC, takayamaki commented
`mastodon/features/hashtag_timeline/index.js` は `mastodon/actions/streaming.js` の
`connectHashtagStream` 関数を経由し、同jsの `connectTimelineStream` 関数内、https://github.com/imas/mastodon/blob/0128b86d3098042cdbc3a1629f74b70f665f8dfb/app/javascript/mastodon/actions/streaming.js#L16-L41
において`/app/javascript/mastodon/stream.js` の `connectStream` 関数を呼び出しています。

当該のexceptionはその `connectStream` 関数内、https://github.com/imas/mastodon/blob/0128b86d3098042cdbc3a1629f74b70f665f8dfb/app/javascript/mastodon/stream.js#L3-L30 の28行目において発生していて、これは `mastodon/actions/streaming.js` の `connectTimelineStream` 関数が `connectStream` 関数に第三引数として渡しているコールバックが何らかの理由によって格納されたオブジェクトのうちonConnectがfunctionでないオブジェクト(またはそもそも格納されていない)にもかかわらず関数として呼ばれたために発生していると考えられます。

というところまでは読みましたが完全な特定には至っていません。
たまたま接続に失敗したなどの偶然ではないかと疑っていますが、複数回試行した際に毎回または高い頻度で発生する程度の再現性があるのでしょうか。

2018-02-01 00:40 UTC, fvh-P commented
リロードしても、再デプロイしても毎回必ず発生します。
stableなバージョンに戻すと発生していません。

また、念のため環境を変えて試しましたがやはり同じ`Uncaught TypeError`が発生します。

2018-02-02 17:46 UTC, fvh-P approved these changes
バグの解消を確認しました。

2018-02-02 18:08 UTC, merged