Proposal: Merge v2.8.0 imastodon
imas/mastodon pull request #225
Opened 2019-06-15 00:14 UTC by acid-chicken

[v2.8.0](https://github.com/tootsuite/mastodon/releases/tag/v2.8.0) のマージ PR になります。

> 投票機能、外したいレベルで嬉しくない()
[2019年3月7日 1:34](https://imastodon.net/@fusagiko/101704666918856217) · [フサギコ (@fusagiko@imastodon.net)](https://imastodon.net/@fusagiko)

> 表示は対応してもいいけど投稿は弾くか…
[2019年3月7日 1:51](https://imastodon.net/@fusagiko/101704733492786920) · [フサギコ (@fusagiko@imastodon.net)](https://imastodon.net/@fusagiko)

と仰っていましたので、API 経由での投票付き投稿を不能にするコミット 7a3715beb0647d0068355ac5e78a168b400252b3 を加えております。

2019-06-15 00:35 UTC, rinsuki commented
2.8.3までは上げるか、修正コミットだけcherrypickしたほうがよさそう (privateな投稿をboostするとpublicになってしまうバグがあるので)
https://github.com/tootsuite/mastodon/pull/10775

2019-06-15 00:40 UTC, rinsuki commented
あと WebUI からも投票作成UI消したほうがいい気がする (もう消してたらごめん)

2019-06-15 00:43 UTC, acid-chicken commented
@rinsuki とりあえず 2.8.3 まで上げることにします。
WebUI の方も同コミットで消しました、説明不足ですみません。

2019-06-15 01:35 UTC, acid-chicken commented
v2.8.3 への追従作業完了しました。

2019-06-15 21:17 UTC, acid-chicken commented
v2.8.3 で止めるメリットが特にあるわけでもないため、そのまま v2.8.4 に追従しました。

2019-06-15 21:21 UTC, acid-chicken commented
ja-IM の新規翻訳ですが、'relationships' を「同僚」と訳しております。
また、'directory' を「社員名簿」と訳すことを提案します。

2019-06-16 10:44 UTC, fvh-P commented
ja-IM に関する追加・変更は別 PR に切り出したほうがいいのかなと思いますがどうでしょうか。

2019-06-16 16:59 UTC, acid-chicken commented
@fvh-P 差し戻しました。

2020-01-02 08:08 UTC, takayamaki commented on app/controllers/api/v1/statuses_controller.rb
> +                                         poll: nil, # Just ignore poll params.
`poll: nil` で無視するのではなく、createメソッドの頭で
`raise Mastodon::ValidationError.new("Can not create vote in this instance.") if status_params[:poll].present?`
的な感じでエラーを返して欲しいです。

2020-01-02 08:22 UTC, takayamaki requested changes
7か月越しになってしまいすみません。

自インスタンスでのpoll作成関連のコードを丸ごと消していただいていますが、消し去ってしまうと本家が弄った際に毎回conflictが生じて都度解消するのに手間がかかってしまいます。

conflict発生による追従の手間を減らすために、React側では`app/javascript/mastodon/features/compose/components/compose_form.js` でPollButtonContainerとPollFormContainerを使わないだけに留めてほしいです。

また`app/controllers/api/v1/statuses_controller.rb`のcreateメソッドにおいてpoll: nil としてパラメーターを無視してしまうと、単に正しく動作していないかのように見えてバグ報告が来る可能性があるので、createメソッドの頭で
`raise Mastodon::ValidationError.new("Can not create poll in this instance.") if status_params[:poll].present?`
のような感じでエラーを返して欲しいです。(できればI18nまでやってほしいですが一旦はベタ書きでも良いです

2020-01-02 20:00 UTC, acid-chicken commented
@takayamaki レビューありがとうございます。アンケート周りは ae2fe65a2d9380c1f7d13ce586df84706d9afbec で変更を一旦差し戻し、バック側を ad3437ea7f5d311f791c156688dc3135f37bc89d にて、フロント側を a77537eba7f9fc5cb02b5e15646897bfc8f3d198 にてレビューに沿いながら再度変更を加えましたので、ご確認ください。また、 01c5053e9e293a1f2bcecf69c2ef0b1a7338e6e7 にてアンケート作成がエラーになるようテストも追加いたしましたので、こちらも加えてご確認いただけるとありがたいです。

2020-02-24 09:17 UTC, takayamaki approved these changes

2020-02-24 09:17 UTC, merged