Enable to show unlisted tagged toots on the hashtag timeline
imas/mastodon pull request #32
Opened 2017-08-06 15:10 UTC by fvh-P

Based on #29 

Currently, only "public" toots with hashtags are flowing to the hashtag timeline (/api/v1/streaming/hashtag), but this modifying enables to flow "unlisted" toots to the hash tag timeline.

現在、ハッシュタグ付きのトゥートについてはpublicなもののみがハッシュタグタイムライン(/api/v1/streaming/hashtag)に流れていますが、unlistedなトゥートでもハッシュタグタイムラインに流れるようにします。

2017-08-07 16:32 UTC, takayamaki submitted a review, later dismissed
LGTM
[![LGTM](https://www.lgtm.in/p/aZMh8XFfq)](https://www.lgtm.in/i/aZMh8XFfq)

PRの規模的に念のため #34 を先にマージしてから取り込むつもり

2017-08-08 06:41 UTC, deflis requested changes
実際の確認まだしてないですが、懸念がありそうな雰囲気があるので修正依頼にしておきます。

2017-08-08 06:41 UTC, deflis commented on app/services/fan_out_on_write_service.rb
> +    return if status.account.silenced? || !status.public_visibility? && !status.unlisted_visibility? || status.reblog?
この下のif文も修正しないと、deliver_to_publicにunlistedも行かないですかね？

2017-08-08 06:50 UTC, fvh-P commented on app/services/fan_out_on_write_service.rb
> +    return if status.account.silenced? || !status.public_visibility? && !status.unlisted_visibility? || status.reblog?
あー書き忘れてましたね()
直します
あと`render_anonymous_payload(status)`ってこのままで大丈夫ですかね

2017-08-08 07:16 UTC, takayamaki commented on app/services/fan_out_on_write_service.rb
> +    return if status.account.silenced? || !status.public_visibility? && !status.unlisted_visibility? || status.reblog?
unlistedなのにLTLまで流れて行ってしまうバグを見落とすとかあまりにもガバガバだったので恥じ入るばかり

render_anonymous_payloadはnodeにredis pub/sub経由でぶん投げるメッセージを生成しているだけなので問題なさそう

2017-08-08 07:32 UTC, fvh-P commented
記憶が1分も持たないことが判明しました（直しました

2017-08-08 07:54 UTC, takayamaki requested changes
![2017-08-08-164450_3840x2028_scrot](https://user-images.githubusercontent.com/24884114/29061518-272f4ed8-7c59-11e7-8259-d7e78528b03d.png)
![2017-08-08-164524_3840x2028_scrot](https://user-images.githubusercontent.com/24884114/29061520-29798140-7c59-11e7-9dd6-d0a5cd9a0fb9.png)

![2017-08-08-165341_1920x2004_scrot](https://user-images.githubusercontent.com/24884114/29061774-291a2dac-7c5a-11e7-94f6-6876a595e4ba.png)
テスト用に使ってる南東タグのリンクをクリックすると初期表示用に/api/v1/timelines/tag/南東が呼ばれるのだけれど、その中で思いっきりdirectとprivateが漏れてる

2017-08-08 08:14 UTC, fvh-P commented
修正しました。自環境で確認したところ大丈夫でした。
確認お願いします。

2017-08-08 08:30 UTC, takayamaki approved these changes

2017-08-08 08:30 UTC, takayamaki commented
LGTM

2017-08-08 08:38 UTC, deflis commented on app/services/fan_out_on_write_service.rb
> +    return if status.account.silenced? || !status.public_visibility? && !status.unlisted_visibility? || status.reblog?
ハッシュタグの付いたリプライはハッシュタグに乗るっぽいけど元からの仕様っぽいので大丈夫そう

2017-08-08 08:40 UTC, deflis approved these changes
[![LGTM](http://www.lgtm.in/p/aZMh8XFfq)](http://www.lgtm.in/i/aZMh8XFfq)

2017-08-08 08:44 UTC, takayamaki commented
というわけで #34 をマージした後でこっちも一緒に取り込みまーす

2017-08-09 16:13 UTC, merged