Merge tag 'v1.5.1' into imastodon
imas/mastodon pull request #34
Opened 2017-08-07 14:15 UTC by lnanase

- Fix conflict
  - #4 Favicon and logo 'imas-atmark' change
    - 本家PRの https://github.com/tootsuite/mastodon/pull/4306 で変更の入ったロゴですが、im@stodonのものを使うように直しています
  - #8 管理者メッセージ欄追加
    - 本家PR #4110 でinitial stateの修正が入るなど、大分変更されていましたので、今の実装に沿うように修正しました

- Locale files update

- 5b0be74 のpendingを戻しました

今回のアップデートで登録ページやaboutページに大分修正が入りますので、
マージ&リリース後管理画面で色々修正する必要があります。

よろしくお願い致します。

2017-08-07 16:23 UTC, takayamaki approved these changes
LGTM
[![LGTM](https://www.lgtm.in/p/ijzwpnC7q)](https://www.lgtm.in/i/ijzwpnC7q)

2017-08-08 02:23 UTC, treby approved these changes
:shipit:

2017-08-08 14:10 UTC, deflis requested changes
他のところよくわからないのでとりあえず言語周りだけ確認してみました。1箇所だけ、バージョンアップにそぐわない箇所があったので確認お願いします。

2017-08-08 14:10 UTC, deflis commented on config/locales/ja-IM.yml
>      reblogged: わかられました
ここの部分、jaだと `さんにブーストされました` になってるので `さんにわかられました` に変更したほうが良さそう

2017-08-08 14:24 UTC, lnanase commented on config/locales/ja-IM.yml
>      reblogged: わかられました
ご指摘有難うございます。
確認したら、本verで変更されたようです。
修正致します。

2017-08-08 14:27 UTC, lnanase commented
皆様、お暑い中レビューして頂きありがとうございました。
@deflis さんからの指摘事項を反映し、再度push致しました。
問題なければ承認と、マージをお願い致します。 🍺

2017-08-08 14:37 UTC, deflis approved these changes
指摘箇所の修正確認しました。

:+1:
[![LGTM](https://lgtm.in/p/m3iIf0zNp)](https://lgtm.in/i/m3iIf0zNp)

2017-08-08 14:39 UTC, merged