[WIP] add POST and DELETE method on api/v1/favourite_tags
imas/mastodon pull request #56
Opened 2017-08-22 08:18 UTC by fvh-P

Add methods that process POST and DELETE request on api/v1/favourite_tags. It enables users to create and remove favourite tags through the API.

usage
+ `POST https://xxxxxx.yy/api/v1/favourite_tags?tag=test&access_token=??????????`
+ `DELETE https://xxxxxx.yy/api/v1/favourite_tags/test?access_token=??????????`

api/v1/favourite_tagsにPOSTとDELETEリクエストを処理するメソッドを追加します。API経由でお気に入りタグの追加・削除が可能になります。

- [x] POST・DELETE処理の実装
- [ ] テストケース追加
- [ ] #48への追従

2017-08-22 08:22 UTC, fvh-P commented on config/routes.rb
> +      resources :favourite_tags, only: [:index, :create, :destroy], param: :tag
ここを
`resource :favourite_tags, only: [:show, :create, :destroy]`
とすると、POSTとDELETEのURLを一致させることができますが、indexメソッドの名前を変更する必要があります。
自分には判断できなかったのでどうすべきか検討お願いします。

2017-08-22 10:13 UTC, takayamaki commented on config/routes.rb
> +      resources :favourite_tags, only: [:index, :create, :destroy], param: :tag
んー、showってメソッド名は動的ではあっても一つの結果をGETするって感じがする。

favourite_tagsの場合は複数のfavourite_tagの一覧(index)をGETするって感じだし、
新しくfavourite_tagを作る場合にはfavourite_tagsの中に投げ込む(post)するって感じ、
DELETEの場合はfavourite_tagsの中の特定の一つを消すって感じのニュアンスなので
そのままでいいんじゃないかなー

実際、/settings/favourite_tagsもそうなってるし。

2017-08-26 14:06 UTC, fvh-P commented
#48 に基づき公開範囲設定を追加しました。

例
+ `POST https://xxxxxx.yy/api/v1/favourite_tags?tag=test&visibility=unlisted&access_token=??????????`
+ `POST https://xxxxxx.yy/api/v1/favourite_tags?tag=test&access_token=??????????`
+ `DELETE https://xxxxxx.yy/api/v1/favourite_tags/test?access_token=??????????`

例の1番目ではtestタグが公開範囲unlistedで登録されます。
2番目ではvisibilityパラメータの設定がされていませんが、この場合はpublicとして登録します。
3番目は解除です。

また既に登録されているタグの公開範囲設定の変更は、登録時と同様にタグ名と新たな公開範囲をパラメータにセットしてPOSTするだけでOKです。

2017-08-26 14:14 UTC, fvh-P commented on app/controllers/api/v1/favourite_tags_controller.rb
> +    @favourite_tag = @account.favourite_tags.where(tag: tag).where.not(visibility: favourite_tag_visibility).first
ちょっとここらへん乱暴かなと思ったのでもっといい書き方があれば変更します。
リクエストとタグ名が同じで公開範囲が異なるものが登録されている場合にはいったん削除して登録しなおす処理です。
whereの後にfirstとしているのは、FavouriteTagクラスにおいてタグ名レベルで重複がないことは保障されている(`where(tag: tag)`で絞り込むときに高々1つしか引っかからない)のでこれで大丈夫だろうという理解です。

2017-08-26 15:53 UTC, deflis commented on config/routes.rb
> +      resources :favourite_tags, only: [:index, :create, :destroy], param: :tag
Webを支える技術とかで読みましたが、REST APIを設計するときの指針として言われているのは

* POSTは（URLのない）リソースを作る。（というかGET/PUT/DELETE以外は、ほぼ全部ここ）
* GETはそのURLのリソースを参照する
* PUTはそのURLのリソースを作る、更新する
* DELETEはそのURLのリソースを削除する

というような感じでした。
その原則に従ってURLを設計すると良いと想います。

2017-08-28 02:19 UTC, fvh-P commented on config/routes.rb
> +      resources :favourite_tags, only: [:index, :create, :destroy], param: :tag
Railsの複数形リソースでは、

リクエスト | パス | コントローラ#アクション
-- | -- | --
GET | /favourite_tags | favourite_tags#index
POST | /favourite_tags | favourite_tags#create
PUT | /favourite_tags/:id | favourite_tags#update
DELETE | /favourite_tags/:id | favourite_tags#destroy

となります。(一部抜粋)
favourite_tagsは複数のお気に入りタグをidで管理しているので、DELETEの時も基本idを指定して削除することになりますが、さすがに呼び出し側にお気に入りタグのidを調べる必要があるのは不親切だろうと思ったので` param: :tag`としてパスを`/favourite_tags/:tag`に変え、タグ名で指定できるようにしています。
また、更新についてはお気に入りタグの場合公開範囲設定を変更するくらいしかないので、わざわざリクエストを分ける必要もないかなあと。

2017-09-02 15:29 UTC, fvh-P commented
specを追加しました。

また、POSTされたタグがすでに登録されていて公開範囲設定も同じであった場合は、お気に入りタグ一覧をJSONで返しますが、既に登録されていて何も変更しなかったことを知らせるためステータスを409 Conflictにしました。

とりあえずAPIの追加、 #48 への追従、テストの追加は完了しましたので、仕様がこれでよいかなど確認お願いします。

2017-09-05 06:29 UTC, deflis commented
同じタグが違う設定で存在する場合に更新、全く同じならエラー、というのはちょっとどうかなと思います。
寄せるならどちらかに寄せたほうが良いかと。

2017-09-05 06:31 UTC, deflis requested changes
同じタグが違う設定であるなら更新、全く同じならエラー、という仕様がややこしいので、同じタグがあるならエラーにして、更新用APIを別で用意するほうが筋が良い方法だと思います。
というわけでNG。

2017-09-05 06:50 UTC, takayamaki commented
RESTなAPIだけだった関係上まだ試せていなかったのでコメントしていませんでしたが、
まあ、更新用エンドポイントを作るなら/api/v1/favourite_tags/tag_nameにPUTメソッド→FavouriteTag#updateですかねぇ

正直、お気に入りタグを違う公開範囲で登録しなおすって（公開範囲連動が実装されたばかりの今はともかく今後は）使用事例としてはかなり少ないと思うので、そこに労力とコード行数を使う必要あるかな？　って感じはする。

2017-09-05 10:51 UTC, fvh-P commented
とりあえずPUTを処理できるようにしました。

--                     | POST | PUT | DELETE
--------------- | ----- | ----- | -------
**未登録のタグ** | 登録する<br>200 OK | 404 Not Found | 404 Not Found
**登録済みのタグ** | 何もしない<br>422 Unprocessable Entity | 一回削除してから登録し直す<br>200 OK | 削除する<br>200 OK

2017-09-05 11:16 UTC, deflis requested changes
422だと渡されたデータがおかしいという意味になるので、既にそのタグ名のデータがありますという意味で409のほうが良いと思います。

2017-09-05 16:14 UTC, lnanase commented on app/controllers/api/v1/favourite_tags_controller.rb
> +      render json: current_favourite_tags, status: :conflict
細かいですが、conflictであるなら、
@account.favourite_tags.find_by(tag: tag)
のようなconflictしてる favourite_tag を返したほうが良さそうな気がします。

2017-09-05 16:18 UTC, lnanase commented on spec/controllers/api/v1/favourite_tags_controller_spec.rb
> +      it 'does not create new favourite_tag and returns http 422' do
422のままです。

2017-09-05 16:22 UTC, lnanase commented on spec/controllers/api/v1/favourite_tags_controller_spec.rb
> +    end
個人的には、updateした結果についての
テストも欲しいところです(このケースではvisibility)

2017-09-06 07:12 UTC, fvh-P commented
--                     | **未登録のタグ** | **登録済みのタグ** 
--------------- | -------------------- | ---------------------- 
**POST** | 登録する<br>登録後のお気に入りタグリストを返す<br>200 OK | 何もしない<br>Conflictしたお気に入りタグ1つを返す<br>409 Conflict
**PUT** | 何もしない<br>現在のお気に入りタグリストを返す<br>404 NotFound | 一回削除してから登録し直す<br>変更後のお気に入りタグリストを返す<br>200 OK
**DELETE** | 何もしない<br>現在のお気に入りタグリストを返す<br>404 NotFound | 削除する<br>削除後のお気に入りタグリストを返す<br>200 OK

2017-09-06 11:01 UTC, fvh-P commented
@takayamaki さんより設計に関する指示がありましたので一旦閉じて新しいPRを開きなおします。

2017-09-06 11:01 UTC, closed without merging